version: '3.5'

services:
  db_auth:
    image: postgres:alpine
    container_name: servletdb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  web-servlet-service:
    build: .
    ports:
      - "8085:8080"
    depends_on:
      - db_auth
    networks:
      - web-servlet-service_default  # присоединяемся к сети

networks:
  web-servlet-service_default:
    external: true  # присоединяемся к внешней сети